import type { Metadata } from "next";
import { SectionTitle } from "../components/SectionTitle";
const title="Analytics Consulting Services | David Edmonds";
const description="Focused dashboards, repeatable reporting and KPI analysis: clear deliverables, validated measures and a practical handoff.";
export const metadata: Metadata={title,description,openGraph:{title,description,images:[]},twitter:{card:"summary",title,description,images:[]}};
const offers=[
 {topic:"health-check",label:"ASSESS THE CURRENT REPORT",title:"Reporting Health Check",fit:"For a team that needs to understand why reports disagree, take too long or leave important questions unanswered.",items:["A review of reporting steps, KPI definitions and data checks","A prioritized list of gaps and practical fixes","A concise findings brief with recommended next steps"],start:"A description of the report, its audience, source systems and the issue you want to resolve.",example:"/work/executive-brief",exampleLabel:"See a sample findings brief"},
 {topic:"dashboards",label:"BUILD A SHARED VIEW",title:"Dashboard Build",fit:"For a team that needs a shared view of performance instead of scattered spreadsheets.",items:["A focused Power BI, Tableau or Excel dashboard","Agreed KPI definitions and filters","Source-to-total validation and handoff notes"],start:"One business question, the intended audience and a description of the available data.",example:"/work/sales-profitability",exampleLabel:"See the sales dashboard"},
 {topic:"reporting",label:"SIMPLIFY RECURRING WORK",title:"Reporting Automation",fit:"For a recurring report that depends on repetitive copying, manual preparation or inconsistent checks.",items:["A review of the current reporting steps","Reusable Excel or SQL preparation and checks","Refresh instructions and documented exceptions"],start:"A walkthrough of the current report, its source systems and how often it is needed.",example:"/tools/what-changed",exampleLabel:"Try the report comparison tool"},
];
export default function ServicesPage(){return <main id="top"><section className="page-intro shell"><span>CONSULTING SERVICES</span><h1>Clear scope.<br/><em>Useful deliverables.</em></h1><p>Bold Proof Analytics is my consulting business. Hands-on analytics support for small teams and operations leaders. Start with the decision or reporting problem; we’ll agree on the output, data requirements and scope before work begins.</p><a className="button blue" href="/contact#inquiry">Discuss your reporting needs <span>→</span></a><div className="case-page-actions"><a className="secondary-action" href="/david-edmonds-capability-statement.pdf" download>Download capability statement ↓</a></div></section>
 <section className="consulting section"><div className="shell"><SectionTitle eyebrow="WAYS TO WORK TOGETHER" title="Choose the support" accent="your team needs."/><div className="offer-grid scoped-offers">{offers.map(o=><article key={o.topic}><small>{o.label}</small><h3>{o.title}</h3><p>{o.fit}</p><h4>What we can deliver</h4><ul>{o.items.map(item=><li key={item}>{item}</li>)}</ul><div className="offer-start"><h4>What we need to begin</h4><p>{o.start}</p></div><div className="offer-links"><a className="button blue" href={`/contact?topic=${o.topic}#inquiry`}>Discuss this service <span>→</span></a><a className="secondary-action" href={o.example}>{o.exampleLabel} →</a></div></article>)}</div><p className="scope-note">The final deliverables, timing and fees depend on data readiness and scope and are agreed before the project starts.</p></div></section>
 <section className="process-section section"><div className="shell"><SectionTitle eyebrow="HOW TO START" title="A practical path from" accent="question to answer."/><div className="process-grid"><article><h3>Share the problem</h3><p>Describe the report or decision, who needs the answer, and what is slow or unclear today.</p></article><article><h3>Agree on the work</h3><p>Review data availability, define the measures and deliverables, and confirm scope, timing and fees.</p></article><article><h3>Build, check and hand over</h3><p>Review the output against the agreed question, validate the measures, and provide instructions your team can use.</p></article></div><div className="fit-note"><div><span>NOT SURE WHICH SERVICE FITS?</span><p>Start with the problem. The first discussion can help identify the right scope.</p></div><a className="button dark" href="/contact#inquiry">Start a conversation <span>→</span></a></div></div></section><section className="compact-cta shell"><div><h2>Consulting through Bold Proof Analytics.</h2><p>Explore the business, or review my independent case studies before starting a conversation.</p></div><div className="case-page-actions"><a className="secondary-action" href="/work/executive-brief">Read the executive brief →</a><a className="button blue" href="https://bold-proof-analytics.pages.dev/">Visit Bold Proof Analytics ↗</a></div></section></main>;}

