import type { Metadata } from "next";

const title = "Startup Operations Dashboards | David Edmonds";
const description = "Seven editable Tableau dashboards with KPI comparisons, operational detail and reconciled financial movements. An independent project using synthetic data.";
const base = "/startup-operations";
export const metadata: Metadata = { title, description, alternates: { canonical: "/work/startup-operations" }, openGraph: { title, description, images: [{ url: `${base}/Expanded-Screenshots/05-Revenue.jpg`, alt: "Tableau recurring revenue dashboard using fictional Northstar data" }] } };
const dashboards = [
  ["Public Status", "01-Public-Status.jpg", "Is service availability within the demo target?", "Weighted uptime, downtime budget and incident detail connect the headline rate to affected services, severity and resolution."],
  ["Live Changelog", "02-Live-Changelog.jpg", "What shipped, and how reliably?", "Release volume, rollback rate and lead time sit alongside the feature mix and recent release history."],
  ["Metrics & Analytics", "03-Metrics-Analytics.jpg", "Where does acquisition turn into activation?", "Sessions, sign-ups and same-day activations make conversion denominators visible, with daily volume context."],
  ["Waitlist Counter", "04-Waitlist-Counter.jpg", "What explains the change in the waiting pool?", "Opening balance plus additions, less conversions and removals, reconciles to the closing balance. Throughput is not cohort conversion."],
  ["Revenue Dashboard", "05-Revenue.jpg", "What moved recurring revenue?", "New MRR, expansion, contraction and churn reconcile the opening and closing run rates. Cash receipts, refunds and customer counts provide supporting context."],
  ["Backend Health Monitor", "06-Backend-Health.jpg", "Which reliability issues need investigation?", "Request-weighted response time, error counts and daily demo-threshold breaches identify periods to investigate."],
  ["Frontend Performance", "07-Frontend-Performance.jpg", "How consistently does the experience meet the demo targets?", "Daily p75 LCP, INP and CLS observations, target attainment days and worst observations reveal performance variation."],
];

export default function StartupOperations() {
  return <main className="case-page startup-case" id="top">
    <section className="case-hero shell"><a className="back-link" href="/work">← Back to portfolio</a><span>TABLEAU · INDEPENDENT PORTFOLIO PROJECT · SYNTHETIC DATA</span><h1>Startup operations.<br/><em>Seven connected views.</em></h1><p>A monthly operating review for a fictional startup: measure service health, understand product and acquisition activity, and reconcile changes in recurring revenue.</p><div className="case-page-actions"><a className="button blue" href={`${base}/Startup-Operations-Expanded.twbx`} download>Download Tableau workbook ↓</a><a className="secondary-action" href="#dashboards">Explore seven dashboards ↓</a><a className="secondary-action" href="https://public.tableau.com/app/profile/david.edmonds5066/viz/Startup-Operations-Expanded/FrontendPerformance" target="_blank" rel="noreferrer">Open interactive Tableau view ↗</a></div><p className="startup-note">Editable packaged workbook with both data extracts included. The previews below are static screenshots captured in Tableau; interactive controls are available in the downloaded workbook.</p></section>
    <section className="case-summary"><div className="shell case-summary-grid"><div><span>THE QUESTION</span><p>What changed this month, what explains it, and which operational signals deserve attention?</p></div><div><span>THE APPROACH</span><p>21 headline metrics with comparisons, 14 trend charts and 14 detail panels, using a shared reporting-month selector.</p></div><div><span>THE DATA</span><p>184 daily records, 26 releases and eight resolved incidents. All data is fictional, covering March–August 2026.</p></div></div></section>
    <section className="section shell" id="dashboards"><h2>Explore the operational review</h2><p>Each view moves from headline performance to trends and supporting detail. These screenshots show August 2026.</p><nav className="project-jump" aria-label="Choose a dashboard">{dashboards.map(([name], i) => <a key={name} href={`#dashboard-${i + 1}`}>{name}</a>)}</nav>
      {dashboards.map(([name, file, question, detail], i) => <article className="startup-dashboard" id={`dashboard-${i + 1}`} key={name}><span className="pill">{String(i + 1).padStart(2, "0")} / 07</span><h3>{name}</h3><p className="lead">{question}</p><p>{detail}</p><figure><a href={`${base}/Expanded-Screenshots/${file}`} aria-label={`Open full-size ${name} screenshot`}><img src={`${base}/Expanded-Screenshots/${file}`} width="1440" height="900" loading="lazy" alt={`${name}: actual Tableau presentation screenshot with August 2026 synthetic startup metrics`}/></a><figcaption>Actual Tableau screenshot · Synthetic data · Select the image for full size.</figcaption></figure></article>)}
    </section>
    <section className="case-method"><div className="shell"><h2>Definitions that keep the analysis honest</h2><div className="method-grid"><article><h3>Reconcile movements</h3><p>Opening-to-ending MRR and waitlist movements balance. Ending balances are not summed across days; rates divide aggregated counts. Monthly headline reconciliation checked 126 sample values.</p></article><article><h3>Separate different measures</h3><p>MRR is a recurring run rate; receipts are cash collection. Waitlist throughput is not cohort conversion. Frontend metrics are daily p75 observations, not monthly percentiles or a 28-day Core Web Vitals assessment.</p></article><article><h3>Make comparison explicit</h3><p>Rates use percentage-point changes. March has no prior-month baseline in the sample. Full-period views distinguish period totals from ending observations.</p></article></div></div></section>
    <section className="section shell"><h2>Use the workbook</h2><ol><li>Download and open the packaged workbook in Tableau.</li><li>Choose one of the seven dashboard tabs and change Reporting month. Cards and detail follow the selection; trends retain all six months.</li><li>Use presentation mode for the full desktop layout. Supporting worksheets remain editable.</li></ol><p>All seven dashboards were inspected in Tableau. This is a demonstration template, with no live feeds, automatic refresh or alerts. Supporting detail is precomputed: changing production data requires rebuilding both extracts together and reconciling the results. The download does not include the refresh toolkit, and real-data replacement has not been validated.</p><div className="case-page-actions"><a className="button blue" href={`${base}/Startup-Operations-Expanded.twbx`} download>Download editable workbook ↓</a><a className="secondary-action" href={`${base}/Expanded-Design-Guide.md`}>Read design specifications</a><a className="secondary-action" href="/contact?topic=dashboards">Discuss a dashboard project →</a></div></section>
  </main>;
}
