'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import { ArrowUpRight, ArrowRight, ArrowDownToLine, ArrowLeftRight, FileSpreadsheet, ShieldCheck, Plus, Minus, Copy, Check, X, Search, SlidersHorizontal } from './icons';
import { compare, parseCSV, numeric, sampleBefore, sampleAfter, csvCell, type Report, type Entry } from './compare';
const fmt = (n: number) => new Intl.NumberFormat('en-US', { maximumFractionDigits: 2 }).format(n);
const signed = (n: number) => (n > 0 ? '+' : '') + fmt(n);
function download(name: string, text: string, type = 'text/plain') { const url = URL.createObjectURL(new Blob([text], { type })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
export default function Home() {
 const [before, setBefore] = useState<Report>(() => parseCSV(sampleBefore, 'july-revenue.csv'));
 const [after, setAfter] = useState<Report>(() => parseCSV(sampleAfter, 'august-revenue.csv'));
 const [key, setKey] = useState('Account ID'), [metric, setMetric] = useState('Revenue');
 const [demo, setDemo] = useState(true), [error, setError] = useState(''), [loading, setLoading] = useState('');
 const [tab, setTab] = useState('Overview'), [filter, setFilter] = useState('All records'), [query, setQuery] = useState('');
 const [selected, setSelected] = useState<Entry | null>(null);
 const shared = before.headers.filter(h => after.headers.includes(h));
 const analysis = useMemo(() => { try { return { result: compare(before, after, key, metric), error: '' }; } catch (e) { return { result: null, error: (e as Error).message }; } }, [before, after, key, metric]);
 const r = analysis.result;
 const drivers = r ? [...r.entries].filter(e => e.delta !== 0).sort((a,b) => Math.abs(b.delta) - Math.abs(a.delta)) : [];
 const summary = r ? `${metric} moved from ${fmt(r.before)} to ${fmt(r.after)} (${signed(r.delta)}${r.before !== 0 ? `; ${signed(r.delta / Math.abs(r.before) * 100)}% relative to the absolute prior total` : '; percentage change unavailable from a zero baseline'}). ${r.added} added IDs, ${r.missing} missing IDs, and ${r.changed} uniquely matched IDs with changed fields. ${drivers.length ? `Largest contribution: ${drivers[0].id}, ${signed(drivers[0].delta)}.` : 'No measure changes.'} ${r.duplicateGroups} IDs need duplicate review; all duplicate rows are included in totals. These are arithmetic contributions, not proven business causes.` : '';
 const rows = r?.entries.filter(e => (filter === 'All records' || e.status === filter || filter === 'Missing' && !e.newRows.length || filter === 'Added' && !e.oldRows.length) && e.id.toLowerCase().includes(query.toLowerCase())) ?? [];
 async function upload(file: File | undefined, side: 'before' | 'after') {
  if (!file) return; setError(''); setLoading(side);
  try { if (!/\.csv$/i.test(file.name)) throw new Error('Choose a .csv file. For Excel reports, save the worksheet as CSV first.'); if (file.size > 5 * 1024 * 1024) throw new Error('Choose a CSV file smaller than 5 MB.');
   const report = parseCSV(await file.text(), file.name); const a = side === 'before' ? report : before, b = side === 'after' ? report : after;
   const cols = a.headers.filter(h => b.headers.includes(h));
   if (!cols.includes(key)) setKey(cols[0] ?? '');
   if (!cols.includes(metric)) setMetric(cols.find(h => [...a.rows.slice(0,100).map(row => row[a.headers.indexOf(h)]), ...b.rows.slice(0,100).map(row => row[b.headers.indexOf(h)])].every(v => numeric(v) !== null)) ?? '');
   (side === 'before' ? setBefore : setAfter)(report); setDemo(false); setSelected(null);
  } catch (e) { setError((e as Error).message); } finally { setLoading(''); }
 }
 function loadDemo() { setBefore(parseCSV(sampleBefore,'july-revenue.csv')); setAfter(parseCSV(sampleAfter,'august-revenue.csv')); setKey('Account ID'); setMetric('Revenue'); setError(''); setDemo(true); setSelected(null); setFilter('All records'); setQuery(''); }
 function evidence() { if (!r) return; const csv = [['ID','Status','Before total','After total','Change','Before record numbers','After record numbers','Changed fields'], ...r.entries.map(e => [e.id,e.status,e.before,e.after,e.delta,e.oldRows.join('; '),e.newRows.join('; '),e.fields.join('; ')])].map(row => row.map(csvCell).join(',')).join('\r\n'); download('what-changed-evidence.csv',csv,'text/csv;charset=utf-8'); }
 function readout() { if(r) download('what-changed-summary.txt',`WHAT CHANGED?\nBefore: ${before.name}\nAfter: ${after.name}\nMatch by: ${key}\nMeasure: ${metric}\n\n${summary}\n\nIDs are trimmed and case-sensitive. Fields are compared as exact text. All rows, including duplicates, contribute to totals. Record numbers exclude the header. Column changes: added ${r.addedColumns.join(', ')||'none'}; removed ${r.removedColumns.join(', ')||'none'}.`); }
 return <div className="report-analyzer"><header className="topbar"><Link className="brand" href="/tools" aria-label="Back to Analytics Lab"><span className="brand-mark"><ArrowLeftRight size={21}/></span>what changed<span className="brand-dot">?</span></Link><span className="top-label">REPORT ANALYZER</span><span className="privacy"><ShieldCheck size={16}/> Files stay on your device</span></header>
 <main><div className="page-heading"><div><div className="eyebrow">THE DIFFERENCE IS IN THE DETAILS</div><h1>Two reports. A clearer picture.</h1><p>Find what changed, what’s missing, and what needs a second look.</p></div><button className="button" onClick={loadDemo}><ArrowLeftRight size={16}/> Load sample reports</button></div>
 <section className="inputs" aria-label="Choose reports"><div className="file-pair">{([{side:'before',report:before,label:'01',title:'Before'},{side:'after',report:after,label:'02',title:'After'}] as const).map(({side,report,label,title}) => <label className="file-card" key={side}><span className="file-step">{label} <b>{title}</b></span><div className="file-main"><span className={'file-icon '+side}><FileSpreadsheet size={25}/></span><div><strong>{loading === side ? 'Reading report…' : report.name}</strong><span>{fmt(report.rows.length)} records · {report.headers.length} columns</span></div><ArrowUpRight className="file-arrow" size={18}/></div><span className="replace">Choose a CSV · <u>browse files</u><span>5 MB max</span></span><input type="file" accept=".csv,text/csv" aria-label={`Choose ${title.toLowerCase()} report`} disabled={!!loading} onChange={e => {void upload(e.target.files?.[0],side); e.target.value='';}}/></label>)}</div><div className="configuration"><div className="config-title"><SlidersHorizontal size={17}/><b>Comparison setup</b></div><label>Match records by<select value={key} onChange={e=>{setKey(e.target.value); setSelected(null);}}><option value="" disabled>Select an ID column</option>{shared.map(h=><option key={h}>{h}</option>)}</select></label><label>Measure the change in<select value={metric} onChange={e=>{setMetric(e.target.value); setSelected(null);}}><option value="" disabled>Select a measure</option>{shared.map(h=><option key={h}>{h}</option>)}</select></label><span className="auto-note"><Check size={15}/> Updates automatically</span></div></section>
 {(error || analysis.error) && <div className="error" role="alert">{error || analysis.error}</div>}
 <div className="workspace-heading"><div><h2>Comparison results</h2><span className="badge">{demo?'Sample data':'Your reports'}</span></div><button className="text-button" onClick={evidence} disabled={!r}><ArrowDownToLine size={16}/> Export evidence</button></div>
 <nav className="tabs" aria-label="Result views">{['Overview','Record changes','Data quality','How it works'].map(t=><button className={tab===t?'active':''} key={t} onClick={()=>{setTab(t);setSelected(null);}}>{t}{t==='Data quality' && r && r.duplicateGroups>0 && <span className="count">{r.duplicateGroups}</span>}</button>)}</nav>
 {r && tab==='Overview' && <><section className="metrics"><article className="metric featured"><span>Total {metric.toLowerCase()} change <ArrowUpRight size={18}/></span><strong>{signed(r.delta)}</strong><div><span className="pill">{r.before===0?'No % baseline':signed(r.delta/Math.abs(r.before)*100)+'%'}</span><small>{fmt(r.before)} → {fmt(r.after)}</small></div></article><article className="metric"><span>Added IDs <Plus size={17}/></span><strong>{r.added}</strong><button onClick={()=>{setTab('Record changes');setFilter('Added');}}>Only in the after report <ArrowRight size={14}/></button></article><article className="metric"><span>Missing IDs <Minus size={17}/></span><strong>{r.missing}</strong><button onClick={()=>{setTab('Record changes');setFilter('Missing');}}>Only in the before report <ArrowRight size={14}/></button></article><article className="metric"><span>Duplicate IDs <Copy size={17}/></span><strong>{r.duplicateGroups}<span className="review-dot"/></strong><button onClick={()=>setTab('Data quality')}>Worth a second look <ArrowRight size={14}/></button></article></section>
 <div className="overview-grid"><section className="panel drivers"><div className="panel-heading"><div><h3>What drove the change?</h3><p>Largest contributions to {metric.toLowerCase()}</p></div><span className="unit">Δ {metric}</span></div><div className="driver-list">{drivers.slice(0,5).map((e,i)=><button className="driver-row" key={e.id} onClick={()=>{setSelected(e);setTab('Record changes');}}><span className="driver-rank">0{i+1}</span><span className="driver-name"><b>{(() => {const report=e.newRows.length?after:before; const n=report.headers.findIndex(h=>/^(account|name|customer|product)$/i.test(h)); return n>=0?report.rows[(e.newRows[0]??e.oldRows[0])-1][n]:e.id;})()}</b><small>{e.id} · {e.status}</small></span><span className="bar-track"><span className={e.delta>=0?'positive':'negative'} style={{width: `${Math.max(2,Math.abs(e.delta)/Math.abs(drivers[0].delta)*100)}%`}}/></span><b className="driver-value">{signed(e.delta)}</b><ArrowUpRight size={14}/></button>)}{!drivers.length && <p className="empty">The selected measure has not changed.</p>}</div><div className="panel-foot">All {drivers.length} contributions reconcile to {signed(r.delta)}.<button className="text-button" onClick={()=>{setTab('Record changes');setFilter('All records');}}>View records <ArrowRight size={14}/></button></div></section>
 <section className="summary"><div className="summary-top"><span className="eyebrow">THE READOUT</span><span className="summary-icon"><ArrowLeftRight size={18}/></span></div><h3>{r.delta>0?'An increase, with a story behind it.':r.delta<0?'A decrease, with details to unpack.':'A steady total. Check the details.'}</h3><p>{summary}</p><div className="summary-bottom"><span>Calculated from your records</span><button className="copy-button" aria-label="Download summary" onClick={readout}><ArrowDownToLine size={17}/></button></div></section></div>
 {r.duplicateGroups>0 && <div className="quality-callout"><span className="quality-symbol">!</span><div><b>A quick data check before you share</b><p>{r.duplicateGroups} duplicate ID group{r.duplicateGroups===1?'':'s'} may affect the totals. Review the source rows before drawing conclusions.</p></div><button className="text-button" onClick={()=>setTab('Data quality')}>Review duplicates <ArrowRight size={16}/></button></div>}</>}
 {r && tab==='Record changes' && <section className="panel record-panel"><div className="panel-heading"><div><h3>Record-level evidence</h3><p>{rows.length} matching IDs · inspect a record for source values</p></div><div className="record-controls"><label className="search"><Search size={16}/><input aria-label="Search record IDs" placeholder="Search IDs…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter records" value={filter} onChange={e=>setFilter(e.target.value)}>{['All records','Added','Missing','Changed','Unchanged','Duplicate ID'].map(v=><option key={v}>{v}</option>)}</select></div></div><div className="table-scroll"><table><thead><tr><th>{key}</th><th>Status</th><th>Before</th><th>After</th><th>Change</th><th>Details</th></tr></thead><tbody>{rows.slice(0,200).map(e=><tr key={e.id}><td><button className="id-button" onClick={()=>setSelected(e)}>{e.id}</button></td><td><span className={'status '+e.status.split(' ')[0].toLowerCase()}>{e.status}</span></td><td>{fmt(e.before)}</td><td>{fmt(e.after)}</td><td><b>{signed(e.delta)}</b></td><td><button className="text-button" onClick={()=>setSelected(e)}>Inspect <ArrowUpRight size={14}/></button></td></tr>)}</tbody></table></div>{!rows.length && <p className="empty">No records match this filter.</p>}{rows.length>200 && <p className="empty">Showing the first 200 IDs. Export evidence for the full comparison.</p>}
 {selected && <div className="detail"><div className="panel-heading"><h3>{selected.id} · source evidence</h3><button className="text-button" aria-label="Close record details" onClick={()=>setSelected(null)}><X size={18}/></button></div><p>{selected.status==='Duplicate ID'?'Multiple rows share this ID. Totals are summed; individual rows have not been paired.':`Changed shared fields: ${selected.fields.join(', ') || 'none'}.`}</p>{([{report:before,numbers:selected.oldRows,label:'Before'},{report:after,numbers:selected.newRows,label:'After'}]).map(s=><div key={s.label}><h4>{s.label} · {s.report.name}</h4>{!s.numbers.length?<p>Record absent.</p>:<div className="table-scroll"><table><thead><tr><th>Record #</th>{s.report.headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{s.numbers.slice(0,100).map(n=><tr key={n}><td>{n}</td>{s.report.rows[n-1].map((v,i)=><td key={i}>{v || '—'}</td>)}</tr>)}</tbody></table>{s.numbers.length>100 && <p>First 100 rows shown. Export evidence for all source record references.</p>}</div>}</div>)}</div>}</section>}
 {r && tab==='Data quality' && <section className="panel quality-panel"><h3>Check the inputs before the conclusions.</h3><p>Duplicate IDs are ambiguous matches. Exact duplicates are repeated full rows beyond the first occurrence.</p><div className="quality-stats"><div><b>{r.duplicateGroups}</b><span>Duplicate ID groups across reports</span></div><div><b>{r.exactOld} / {r.exactNew}</b><span>Exact duplicate extra rows · before / after</span></div><div><b>{r.addedColumns.length} / {r.removedColumns.length}</b><span>Columns added / removed</span></div></div><h4>IDs to review</h4>{r.entries.filter(e=>e.status==='Duplicate ID').map(e=><button className="quality-item" key={e.id} onClick={()=>{setSelected(e);setTab('Record changes');}}><b>{e.id}</b><span>{e.oldRows.length} before rows → {e.newRows.length} after rows</span><span>Contribution {signed(e.delta)}</span><ArrowUpRight size={17}/></button>)}{!r.duplicateGroups && <p>No duplicate IDs found.</p>}<h4>Column changes</h4><p>Added: {r.addedColumns.join(', ')||'None'}<br/>Removed: {r.removedColumns.join(', ')||'None'}</p><p className="method-note">Every source row is counted in totals, including duplicates. Shared columns are compared; added or removed columns are reported here separately. No records are deleted or corrected.</p></section>}
 {tab==='How it works' && <section className="panel methods"><h3>Transparent by design.</h3><div className="method-grid"><article><span>01</span><h4>Bring two CSV reports</h4><p>Choose a before and after report with a header row, up to 5 MB and 50,000 records each. Save Excel worksheets as comma-separated CSV. UTF-8 text, quoted commas and multiline cells are supported.</p></article><article><span>02</span><h4>Choose an ID and a measure</h4><p>Use a stable ID shared by both files. IDs are trimmed and case-sensitive; leading zeros are preserved. Blank IDs block comparison. Measures must be plain numbers; blank or non-numeric values are never silently treated as zero.</p></article><article><span>03</span><h4>Follow the evidence</h4><p>Each ID contributes its after total minus its before total. Duplicate IDs use summed values and are flagged. Changed fields use exact text comparisons across shared columns. Record numbers start at 1 after the header, ignoring empty lines.</p></article><article><span>04</span><h4>Keep the interpretation honest</h4><p>Contributions explain the arithmetic, not the business cause. All rows count, including duplicates. Percentages use the absolute prior total and are unavailable at zero. Display values round to two decimals; calculations use unrounded values.</p></article></div><div className="method-note"><ShieldCheck size={19}/><p>Report contents are processed in browser memory. This tool does not upload or save your reports. Refreshing resets to the synthetic sample. Downloaded evidence contains your record IDs and should be handled like your source reports.</p></div><button className="button" onClick={()=>download('july-revenue.csv',sampleBefore,'text/csv')}>Download before sample <ArrowDownToLine size={16}/></button> <button className="button" onClick={()=>download('august-revenue.csv',sampleAfter,'text/csv')}>Download after sample <ArrowDownToLine size={16}/></button></section>}
 {!r && tab!=='How it works' && <div className="panel empty"><h3>Ready when your reports are.</h3><p>Choose shared columns and resolve the message above to see a reliable comparison.</p></div>}
 <footer><span><span className="footer-mark">↔</span> Less detective work. More clarity.</span><button onClick={()=>setTab('How it works')}>Methodology & privacy <ArrowUpRight size={13}/></button><span>Built for a closer look.</span></footer></main></div>;
}
