import type { Metadata } from 'next';
import { SalesJourney } from '../../components/SalesJourney';
import { ProjectContact } from '../../components/ProjectContact';
import { comparePlans, example } from '../../tools/profit-planner/model';
const title='Profit Scenario Planner Case Study | David Edmonds';
const description='An independent browser-based planning tool connecting price, volume, discounts and costs to operating profit, break-even sales and a reconciled change explanation.';
export const metadata:Metadata={title,description,alternates:{canonical:'/work/profit-scenario-planner'},openGraph:{title,description,url:'/work/profit-scenario-planner',images:[]},twitter:{card:'summary',title,description,images:[]}};
const sample=comparePlans(example,{...example,price:105,units:950});
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
export default function ProfitPlannerCase(){return <main id="top">
  <section className="case-hero shell"><a className="back-link" href="/work">← Back to Work</a><span>SCENARIO ANALYSIS · UNIT ECONOMICS · VALIDATION</span><h1>Test the decision.<br/><em>See the trade-offs.</em></h1><p>A compact planning tool that shows how changes in price, sales volume, discounts and costs affect monthly operating profit—and explains the difference.</p><div className="case-page-actions"><a className="button blue" href="/tools/profit-planner">Try the planner <span>→</span></a><a className="secondary-action" href="https://github.com/David-Edmonds/David-Edmonds.github.io/tree/main/app/tools/profit-planner">View calculations on GitHub ↗</a></div><p className="safe-project-note">Independent portfolio example · fictional monthly assumptions · USD · no client outcomes.</p></section>
  <section className="case-summary"><div className="shell case-summary-grid"><div><span>THE BUSINESS QUESTION</span><p>Would a higher price still improve profit if fewer units sold?</p></div><div><span>MY APPROACH</span><p>Model the unit economics, compare two sets of assumptions, and reconcile five contributions to the profit change.</p></div><div><span>THE DELIVERABLE</span><p>A browser-only planner with editable inputs, break-even and target-volume calculations, and a downloadable summary.</p></div></div></section>
  <section className="planner-case-example shell" aria-labelledby="worked-title"><div className="dashboard-heading"><div><span>WORKED EXAMPLE</span><h2 id="worked-title">Less revenue. More operating profit.</h2></div><p>A 5% higher list price and 5% lower volume, with the discount and costs unchanged. These are supplied assumptions, not a forecast of demand.</p></div><div className="planner-case-stats"><div><span>BASELINE PROFIT / MONTH</span><strong>{money(sample.before.profit)}</strong><small>1,000 units · $100 list price</small></div><div><span>SCENARIO PROFIT / MONTH</span><strong>{money(sample.after.profit)}</strong><small>950 units · $105 list price</small></div><div><span>MODELED PROFIT CHANGE</span><strong>+{money(sample.delta)}</strong><small>Before interest and tax</small></div></div><p>Both plans use a 5% discount, $55 variable cost per unit and $25,000 monthly fixed costs. Net revenue falls from {money(sample.before.revenue)} to {money(sample.after.revenue)}, while higher contribution per unit more than offsets the lost volume.</p>
  <div className="planner-case-table"><table><caption>Every contribution reconciles to the operating-profit change</caption><thead><tr><th scope="col">Assumption changed</th><th scope="col">Effect on monthly profit</th></tr></thead><tbody>{sample.drivers.map(d=><tr key={d.label}><th scope="row">{d.label}</th><td>{d.value>0?'+':''}{money(d.value===0?0:d.value)}</td></tr>)}</tbody><tfoot><tr><th scope="row">Total change</th><td>+{money(sample.delta)}</td></tr></tfoot></table></div><p className="safe-project-note">Sequential order: volume, list price, discount, variable cost, then fixed costs. Individual contributions depend on that order; the total does not.</p><div className="method-grid"><article><h3>Know the minimum volume</h3><p>The scenario breaks even at {sample.after.breakEven} whole units. It needs {sample.requiredUnits} units to match baseline profit, compared with 950 units planned.</p></article><article><h3>Expose the assumptions</h3><p>Price changes do not automatically produce a demand estimate. Visitors supply the expected volume response and can test several possibilities.</p></article><article><h3>Carry the evidence forward</h3><p>The text download includes both input sets, outputs, the driver breakdown, formulas and limitations. Inputs stay in the browser.</p></article></div></section>
  <section className="section shell"><div className="dashboard-heading"><div><span>CALCULATIONS AND CHECKS</span><h2>A model you can inspect.</h2></div></div><div className="method-grid"><article><h3>Transparent formulas</h3><p>Contribution per unit equals discounted selling price less variable cost. Operating profit equals units times contribution, less fixed costs. Break-even rounds up to whole units.</p></article><article><h3>Tested edge cases</h3><p>Checks cover simultaneous assumption changes, zero revenue, negative contribution, invalid inputs, and the minimum units needed to break even or match baseline profit.</p><a href="https://github.com/David-Edmonds/David-Edmonds.github.io/blob/main/tests/profit-planner.test.mjs">Read the model checks ↗</a></article><article><h3>Visible limits</h3><p>The model assumes one product or stable product mix and constant unit costs within capacity. It excludes demand forecasting, capacity changes, tax, interest, inventory timing and cash flow.</p></article></div></section>
  <SalesJourney current="planner"/>
  <ProjectContact source="profit-planner" topic="analysis" title="Need to test a business decision?" description="Discuss a scenario model with clear assumptions, useful comparisons and checks that your team can follow."/>
 </main>;}
