import type { Finding } from "../components/KeyFindings";

export const salesFindings: Finding[] = [
  {metric:"12.7% vs 7.9%",title:"Revenue outpaces profit",evidence:"2025 revenue reached $8.24M, up 12.7%. Gross profit reached $2.57M, up 7.9%; margin fell about 1.4 percentage points to 31.2%.",implication:"Review margin alongside sales growth before judging performance.",href:"/sql-sales/results/01_performance.csv",source:"Annual performance results"},
  {metric:"−$115K",title:"Margin pressure offsets growth",evidence:"Revenue growth contributes $302,455.59 to gross profit. The margin effect offsets $115,095.05, leaving a reconciled $187,360.54 increase.",implication:"Investigate pricing, discounts, costs and mix. This decomposition does not identify the business cause.",href:"/sql-sales/results/03_profit_drivers.csv",source:"Reconciled profit contributions"},
  {metric:"$313K below plan",title:"Start the regional review in West",evidence:"West reaches 88.3% of its annual revenue plan, a $312,710.96 shortfall—the largest regional gap in the sample.",implication:"Check West’s plan assumptions and segment performance before choosing an intervention.",href:"/sql-sales/results/05_regional_plan.csv",source:"Regional plan results"},
];
export const sqlFindings: Finding[] = [
  {metric:"$783K + $144K",title:"More orders explain most revenue growth",evidence:"The order-count contribution is $782,979.78; revenue per order contributes $144,138.98. Together they reconcile to $927,118.76 of growth.",implication:"Separate order volume from revenue per order; the latter combines price, discounts, basket size and mix.",href:"/sql-sales/results/02_revenue_drivers.csv",source:"Revenue driver results"},
  {metric:"Furniture: −4.0 pp",title:"Category pressure is concentrated",evidence:"Furniture margin falls about 4.0 percentage points to 19.7%, the largest category decline. Other category margins change only slightly.",implication:"Prioritize a Furniture cost, discount and mix review. Within-category effects exclude shifts in category revenue mix.",href:"/sql-sales/results/04_category_pressure.csv",source:"Category margin results"},
  salesFindings[2],
];
export const federalFindings: Finding[] = [
  {metric:"$778.4B",title:"FY2025 leads the modeled period",evidence:"Modeled obligations were $746.4B in FY2023, $740.9B in FY2024 and $778.4B in FY2025.",implication:"Investigate agency contributions to the increase. Obligations represent commitments, not cash outlays.",href:"#validated-results",source:"Validated fiscal-year totals"},
  {metric:"68.2% competed",title:"Competition needs agency context",evidence:"Competed obligations represent 68.2% of the modeled base; sole-source obligations represent 31.8%.",implication:"Compare competition within agency and award context before drawing procurement-policy conclusions.",href:"/federal-contracting-dashboard.jpg",source:"Published dashboard snapshot"},
  {metric:"22.9%",title:"Participation is not goal attainment",evidence:"Small businesses account for 22.9% of total modeled obligations. SBA attainment uses eligible dollars and matching agency, year and category goals.",implication:"Use the correctly scoped goal measure to assess attainment; these different denominators cannot be compared directly.",href:"#quality-control",source:"Measure definitions and limitations"},
];
export const evFindings: Finding[] = [
  {metric:"114,494 Teslas",title:"One make leads the snapshot",evidence:"Tesla represents about 41.0% of the 279,081 vehicles shown in the published, unfiltered dashboard snapshot.",implication:"Explore manufacturer concentration by county and vehicle type before applying a statewide pattern locally.",href:"/washington-ev-dashboard.png",source:"July 30, 2026 dashboard snapshot"},
  {metric:"King County",title:"Volume is geographically concentrated",evidence:"King is the top county by registered EV count in the snapshot. The map displays counts, rather than population-adjusted adoption rates.",implication:"Use counts for scale; add population or total-vehicle denominators before comparing adoption penetration.",href:"/washington-ev-dashboard.png",source:"County map and top-county KPI"},
  {metric:"60,091 · MY2023",title:"Model year describes fleet composition",evidence:"Model year 2023 has the largest cohort in the snapshot, at 60,091 vehicles. These are model years of registered vehicles, not registration dates.",implication:"Do not interpret the lower counts for newer model years as a measured decline in annual registrations.",href:"/washington-ev-dashboard.png",source:"Model-year distribution"},
];
