import type { Metadata } from "next";
import { SectionTitle } from "../components/SectionTitle";

const title = "Analytics Portfolio | David Edmonds";
const description = "Selected Tableau, Power BI, operational analytics, reporting, and data visualization work by David Edmonds.";
const image = "/federal-contracting-dashboard.jpg";
export const metadata: Metadata = { title, description, alternates:{canonical:"/work"}, openGraph:{title,description,url:"/work",images:[{url:image,alt:"Federal Contracting Performance dashboard"}]}, twitter:{card:"summary_large_image",title,description,images:[image]} };

export default function WorkPage() {
  return <main id="top">
    <section className="page-intro shell"><span>SELECTED WORK</span><h1>Analytics work,<br/><em>shown with context.</em></h1><p>Public and sanitized examples that demonstrate dashboard design, KPI thinking, data quality, reporting systems, and decision-focused analysis.</p></section>

    <section className="section shell work-page"><SectionTitle eyebrow="01 · FEATURED" title="Dashboards built for" accent="clear decisions." />
      <article className="feature"><div className="feature-visual"><div className="browser-bar"><i/><i/><i/><span>WASHINGTON EV MARKET OVERVIEW</span></div><img src="/washington-ev-dashboard.png" alt="Washington EV Market Overview dashboard in Tableau"/></div><div className="feature-copy"><span className="pill">TABLEAU CASE STUDY</span><h3>Washington EV Market Overview</h3><p className="lead">An executive dashboard that makes a large public dataset easy to explore without losing the important patterns.</p><div className="case-row"><b>Question</b><p>How are electric vehicles distributed across Washington’s counties, manufacturers, vehicle types, and model years?</p></div><div className="case-row"><b>My work</b><p>KPI hierarchy, dynamic filtering, geographic analysis, dashboard UX, and data-quality controls.</p></div><div className="chips"><span>Tableau</span><span>Market analysis</span><span>Data quality</span><span>Data storytelling</span></div><div className="project-actions"><a className="button blue" href="/work/washington-ev-market">View case study <span>→</span></a><a className="secondary-action" href="https://public.tableau.com/app/profile/david.edmonds5066/viz/WashingtonEVMarketOverview/Dashboard1#1" target="_blank" rel="noreferrer">Open in Tableau ↗</a><a className="secondary-action" href="https://github.com/David-Edmonds/washington-ev-analytics" target="_blank" rel="noreferrer">Project files ↗</a></div></div></article>
      <article className="feature feature-federal"><div className="feature-visual federal-visual"><div className="browser-bar"><i/><i/><i/><span>FEDERAL CONTRACTING PERFORMANCE</span></div><img src="/federal-contracting-dashboard.jpg" alt="Federal Contracting Performance dashboard in Power BI"/></div><div className="feature-copy"><span className="pill">POWER BI PUBLIC-DATA CASE STUDY</span><h3>Federal Contracting Performance</h3><p className="lead">An executive view of federal award activity, small-business participation, and socioeconomic goal performance.</p><div className="case-row"><b>Question</b><p>Where is federal contract spending concentrated, and how are agencies performing against small-business goals?</p></div><div className="case-row"><b>My work</b><p>Power BI modeling, DAX measures, agency and fiscal-year filters, KPI design, and visual theme refinement.</p></div><div className="chips"><span>Power BI</span><span>DAX</span><span>Data modeling</span><span>Executive reporting</span></div><div className="project-actions"><a className="button blue" href="/work/federal-contracting-performance">View case study <span>→</span></a><a className="secondary-action" href="/contact">Discuss this project ↗</a><span className="safe-project-note">Independent public federal-award data · PBIX and source files are not published.</span></div></div></article>
      <div className="portfolio-strip"><span>PORTFOLIO NOTE</span><p><b>Built with real work, shared responsibly.</b> Client-confidential data is never placed on the public site.</p><a href="https://github.com/David-Edmonds" target="_blank" rel="noreferrer">Browse GitHub ↗</a></div>
      <div className="case-study-grid"><article><div className="case-index"><span>03</span><b>CURRENT ROLE · CONFIA SOLUTIONS, LLC</b></div><div className="case-badge blue-badge">POWER BI + EXCEL</div><h3>Recruiting &amp; Operational Analytics</h3><p>Biweekly analysis and leadership reporting across headcount, pipeline stages, time-to-fill, conversion rates, applicant volume, placements, and revenue pipeline metrics.</p><dl><div><dt>Focus</dt><dd>Hiring performance and workforce trends</dd></div><div><dt>Contribution</dt><dd>Dashboard design, KPI tracking, source consolidation, and validation</dd></div></dl><div className="skill-chips static-chips"><span>Power BI</span><span>Excel</span><span>KPI reporting</span><span>Data quality</span></div></article><article><div className="case-index"><span>04</span><b>SANITIZED EXPERIENCE</b></div><div className="case-badge coral-badge">DEFENSE ANALYTICS</div><h3>Metrics &amp; Visualization Portfolio</h3><p>A high-volume reporting portfolio created as the sole data analyst on a 12-person team, spanning executive dashboards, analytical models, reports, and process maps.</p><div className="case-stats"><div><strong>50+</strong><span>visualization products</span></div><div><strong>20+</strong><span>projects supported</span></div></div><div className="skill-chips static-chips"><span>Power BI</span><span>Excel</span><span>Requirements</span><span>Executive reporting</span></div></article></div>
    </section>
  </main>;
}
