import { SectionTitle } from "./components/SectionTitle";

export default function Home() {
  return <main id="top">
    <section className="hero shell">
      <div className="hero-text"><div className="status">PORTFOLIO · OPEN TO REMOTE ANALYTICS ROLES</div><h1>Understand performance.<br/><em>Explain the change.</em></h1><p>I’m David Edmonds, a Data Analytics Consultant with Confia Solutions, LLC. My work covers operational reporting, dashboard development and performance analysis: defining the measures, checking the data and explaining what the results mean.</p><div className="hero-actions"><a className="button blue" href="/work">View my work <span>→</span></a><a className="underlink" href="/david-edmonds-resume.pdf">Read my resume</a></div></div>
      <div className="hero-side"><div className="portrait-wrap"><img src="/david-edmonds.jpg" alt="David Edmonds, Senior Data Analyst and BI Professional"/><div className="portrait-accent"/></div><div className="hero-facts"><div><strong>10+</strong><span>years across public &amp; private sectors</span></div><div><strong>100+</strong><span>analytical and reporting products delivered</span></div></div></div>
    </section>

    <section className="home-work section"><div className="shell"><SectionTitle eyebrow="SELECTED WORK" title="The question, the analysis," accent="and the evidence." />
      <div className="project-preview-grid home-project-grid">
        <article><div className="project-image"><img src="/sales-profitability/dashboard.png" alt="Excel sales and profitability dashboard connected to a SQL investigation"/></div><div><span>EXCEL + SQL · FICTIONAL DATA</span><h3>Sales &amp; Profitability</h3><dl className="home-project-story"><dt>The question</dt><dd>Is sales growth producing stronger profit?</dd><dt>The approach</dt><dd>Reconcile revenue and margin contributions in Excel and SQL.</dd><dt>Explore</dt><dd>A guided dashboard tour, five SQL queries and downloadable project files.</dd></dl><div className="home-project-links"><a href="/work/sales-profitability#walkthrough">Take the walkthrough →</a><a href="/work/sql-sales-investigation">Read the SQL investigation →</a></div></div></article>
        <article><div className="project-image federal"><img src="/federal-contracting-dashboard.jpg" alt="Federal Contracting Performance Power BI dashboard"/></div><div><span>POWER BI · PUBLIC DATA</span><h3>Federal Contracting Performance</h3><dl className="home-project-story"><dt>The question</dt><dd>Where are federal awards concentrated, and how does participation vary?</dd><dt>The approach</dt><dd>Compare agencies and fiscal years, with separate measures for participation and goal attainment.</dd><dt>Explore</dt><dd>The dashboard, data model and validation checks.</dd></dl><div className="home-project-links"><a href="/work/federal-contracting-performance">View Power BI case study →</a></div></div></article>
        <article><div className="project-image"><img src="/washington-ev-dashboard.png" alt="Washington EV Market Overview Tableau dashboard"/></div><div><span>TABLEAU · PUBLIC DATA</span><h3>Washington EV Market Overview</h3><dl className="home-project-story"><dt>The question</dt><dd>How are registered EVs distributed across counties, manufacturers and vehicle types?</dd><dt>The approach</dt><dd>Compare fleet counts and composition, with filters for geographic and vehicle characteristics.</dd><dt>Explore</dt><dd>The interactive Tableau dashboard and the limits of registration data.</dd></dl><div className="home-project-links"><a href="/work/washington-ev-market">View Tableau case study →</a></div></div></article>
      </div><a className="section-link" href="/work">Browse all Work <span>→</span></a>
    </div></section>

    <section className="home-proof section shell"><div><span>EXPERIENCE</span><strong>10+ years</strong><small>Analytics, reporting, and decision support</small></div><div><span>TOOLS</span><strong>Power BI · Tableau · SQL</strong><small>Plus Excel, Python, PostgreSQL, and SharePoint</small></div><div><span>EDUCATION</span><strong>B.S. Analytics</strong><small>Purdue Global · 2024</small></div></section>

    <section className="calculator-teaser"><div className="shell"><div><span>INTERACTIVE TOOLS</span><h2>Try the analysis with your own inputs.</h2><p>Compare reports, check a CSV, estimate reporting effort or test profit assumptions. Each tool runs in your browser.</p></div><a className="button blue" href="/tools">Open the analytics lab <span>→</span></a></div></section>

    <section className="contact compact-contact"><div className="shell contact-grid"><div><span>CAREER &amp; CONSULTING</span><h2>Let’s find the right <em>next step.</em></h2></div><div><p>Contact me about remote analytics roles or questions about my work. For consulting services and project inquiries, visit Bold Proof Analytics.</p><a className="button dark" href="/contact">Contact David <span>↗</span></a><p><a className="underlink" href="https://bold-proof-analytics.pages.dev/">Explore Bold Proof Analytics ↗</a></p></div></div></section>
  </main>;
}
