"use client";
import { ChangeEvent, FormEvent, useMemo, useState } from "react";

const services=[
  ["01","Dashboards & BI","Decision-ready Power BI and Tableau dashboards built around the questions your team actually asks."],
  ["02","Reporting automation","Replace fragile, repetitive reporting with reliable workflows in SQL, Excel, and modern BI tools."],
  ["03","KPI & data quality","Clarify metric definitions, surface data issues, and create a trusted foundation for reporting."],
  ["04","Operational analytics","Turn day-to-day business data into focused insights, practical forecasts, and clear next actions."],
];
const cases=[
  ["OPERATIONS","Executive performance command center","A unified KPI view that replaced disconnected weekly reports and made performance gaps visible at a glance.","12+","reports unified","Power BI · SQL · KPI Design"],
  ["AUTOMATION","Recurring reporting workflow","A refreshable reporting system that reduced manual spreadsheet work and improved delivery consistency.","8h","saved weekly","Excel · Power Query · Automation"],
  ["DATA QUALITY","Analytics-ready data pipeline","A practical validation layer for finding missing values, duplicate records, and schema drift before reporting.","4x","faster QA","Python · SQL · QA"],
];
function parseLine(line:string){const v:string[]=[];let c="",q=false;for(let i=0;i<line.length;i++){const x=line[i];if(x==='"'){if(q&&line[i+1]==='"'){c+='"';i++;}else q=!q;}else if(x===","&&!q){v.push(c.trim());c="";}else c+=x;}v.push(c.trim());return v;}
type Check={rows:number;columns:number;missing:number;duplicates:number;irregular:number;score:number;fields:string};

export default function Home(){
 const [hours,setHours]=useState(10),[people,setPeople]=useState(2),[rate,setRate]=useState(45),[auto,setAuto]=useState(70); const [check,setCheck]=useState<Check|null>(null),[file,setFile]=useState(""),[copied,setCopied]=useState(false);
 const save=useMemo(()=>{const h=hours*people*52*auto/100;return {h:Math.round(h),y:Math.round(h*rate),m:Math.round(h*rate/12)}},[hours,people,rate,auto]);
 function inspect(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setFile(f.name);const r=new FileReader();r.onload=()=>{const lines=String(r.result||"").replace(/^\uFEFF/,"").trim().split(/\r?\n/).filter(Boolean);const head=parseLine(lines[0]||"");const rows=lines.slice(1).map(parseLine);const missing=rows.flat().filter(x=>!x).length,duplicates=rows.length-new Set(rows.map(x=>JSON.stringify(x))).size,irregular=rows.filter(x=>x.length!==head.length).length,total=Math.max(rows.length*head.length,1);const penalty=missing/total*55+duplicates/Math.max(rows.length,1)*30+irregular/Math.max(rows.length,1)*35;setCheck({rows:rows.length,columns:head.length,missing,duplicates,irregular,score:Math.max(0,Math.round(100-penalty)),fields:head.slice(0,3).join(", ")})};r.readAsText(f)}
 async function copy(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);await navigator.clipboard.writeText(`Project inquiry\nName: ${d.get("name")}\nCompany: ${d.get("company")}\nEmail: ${d.get("email")}\nProject: ${d.get("project")}`);setCopied(true);setTimeout(()=>setCopied(false),2000)}
 return <main>
  <nav className="nav shell"><a className="brand" href="#top"><span>DE</span> David Edmonds</a><div className="navlinks"><a href="#services">Services</a><a href="#work">Work</a><a href="#tools">Tools</a><a href="#about">About</a></div><a className="nav-cta" href="#contact">Start a project ↗</a></nav>
  <section className="hero shell" id="top"><div className="eyebrow"><i/> Available for select projects</div><h1>Clear data.<br/><em>Better decisions.</em></h1><p>I turn messy data and manual reporting into trusted KPIs, useful dashboards, and automated workflows.</p><div className="actions"><a className="button primary" href="#work">Explore my work ↓</a><a href="#contact"><b>Discuss a project ↗</b></a></div><div className="herofoot"><span>DATA ANALYTICS<br/>&amp; BI CONSULTANT</span><hr/><span>POWER BI · TABLEAU · SQL<br/>EXCEL · AUTOMATION</span></div></section>
  <div className="ticker">POWER BI　✦　TABLEAU　✦　SQL　✦　EXCEL　✦　KPI STRATEGY　✦　AUTOMATION　✦</div>
  <section className="section shell" id="services"><Header n="01 / SERVICES" a="From raw data to" b="real clarity."/><div className="servicegrid">{services.map(s=><article key={s[0]}><small>{s[0]}</small><h3>{s[1]}</h3><p>{s[2]}</p><b>↗</b></article>)}</div></section>
  <section className="work section" id="work"><div className="shell"><Header n="02 / SELECTED WORK" a="Built to make an" b="operational difference."/><div className="casegrid">{cases.map((c,i)=><article className={`case c${i}`} key={c[1]}><small>{c[0]}　 0{i+1}</small><div className="metric"><strong>{c[3]}</strong><span>{c[4]}</span></div><h3>{c[1]}</h3><p>{c[2]}</p><b>{c[5]}</b></article>)}</div><aside>Representative portfolio examples use synthetic, sanitized data only.</aside></div></section>
  <section className="section shell" id="tools"><Header n="03 / INTERACTIVE TOOLS" a="Put your reporting" b="to the test."/><div className="tools">
   <article className="tool"><Kicker/><h3>Reporting savings calculator</h3><p>Estimate the time and cost your team could recover through automation.</p><div className="calc"><div className="inputs"><label>Weekly reporting hours <b>{hours}</b><input type="range" min="1" max="40" value={hours} onChange={e=>setHours(+e.target.value)}/></label><label>People involved<input type="number" min="1" value={people} onChange={e=>setPeople(+e.target.value||1)}/></label><label>Hourly cost ($)<input type="number" min="1" value={rate} onChange={e=>setRate(+e.target.value||1)}/></label><label>Automatable work <b>{auto}%</b><input type="range" min="10" max="95" step="5" value={auto} onChange={e=>setAuto(+e.target.value)}/></label></div><div className="result"><small>ESTIMATED ANNUAL IMPACT</small><strong>{save.h.toLocaleString()}</strong><span>hours recovered / year</span><hr/><b>${save.y.toLocaleString()}</b><span>annual capacity value</span><p>≈ ${save.m.toLocaleString()} every month</p></div></div></article>
   <article className="tool"><Kicker/><h3>Data quality checker</h3><p>Run a quick first-pass check on a sanitized CSV. Your file stays in this browser.</p><label className="drop"><input type="file" accept=".csv,text/csv" onChange={inspect}/><i>↑</i><b>{file||"Choose a sanitized CSV"}</b><span>Click to browse · CSV only · never uploaded</span></label>{check?<div className="quality"><div><small>QUALITY SCORE</small><strong>{check.score}</strong><span>/ 100</span></div><ul><li><b>{check.rows}</b> rows</li><li><b>{check.columns}</b> columns</li><li><b>{check.missing}</b> empty cells</li><li><b>{check.duplicates}</b> duplicate rows</li><li><b>{check.irregular}</b> irregular rows</li><li><b>{check.fields||"—"}</b> sampled fields</li></ul></div>:<div className="privacy">✓　<b>Client-data safe.</b> Use only public, synthetic, or sanitized data.</div>}</article>
  </div></section>
  <section className="about section" id="about"><div className="shell aboutgrid"><div><small>04 / ABOUT</small><h2>Business-first analytics,<br/><em>built with care.</em></h2></div><div className="aboutcopy"><h3>I’m David Edmonds, a Data Analytics &amp; BI Consultant focused on making reporting clearer, faster, and more useful.</h3><p>My work connects the technical details—data models, calculations, quality checks—with the business decisions they need to support.</p><div className="focus"><p><b>BI</b> Dashboards that answer real business questions</p><p><b>QA</b> Reliable data and well-defined KPIs</p><p><b>AUTO</b> Less manual work, more time to act</p></div><div className="links"><a href="https://github.com/David-Edmonds" target="_blank">GitHub ↗</a><a href="https://www.linkedin.com/in/david-edmonds" target="_blank">LinkedIn ↗</a></div></div></div></section>
  <section className="resume shell"><div><small>EXPERIENCE / FOCUS</small><h2>Analytics that moves<br/>work forward.</h2></div><div><article><b>DATA ANALYTICS &amp; BI CONSULTING</b><span>Current focus</span><p>Dashboard strategy, operational reporting, KPI design, data quality, and workflow automation.</p></article><article><b>TOOLKIT</b><span>Daily practice</span><p>Power BI · Tableau · SQL · Excel · Power Query · Python · GitHub</p></article><a className="button outline" href="#contact">Request full resume ↗</a></div></section>
  <section className="contact" id="contact"><div className="shell contactgrid"><div><small>05 / START A CONVERSATION</small><h2>Have a reporting problem worth <em>solving?</em></h2><p>Tell me where the process is slow, unclear, or unreliable. I’ll help you find the practical next step.</p></div><form onSubmit={copy}><div className="row"><label>Your name<input name="name" required placeholder="Jane Smith"/></label><label>Work email<input name="email" type="email" required placeholder="jane@company.com"/></label></div><label>Company / team<input name="company" placeholder="Acme Operations"/></label><label>What would you like to improve?<textarea name="project" required rows={4} placeholder="We spend 10 hours each week combining reports..."/></label><button className="button primary">{copied?"Inquiry copied ✓":"Copy project inquiry ↗"}</button><small>Copy your inquiry, then send it through LinkedIn. No details are stored.</small></form></div></section>
  <footer className="footer shell"><a className="brand" href="#top"><span>DE</span> David Edmonds</a><p>Data Analytics &amp; BI Consultant<br/>Building clarity from complexity.</p><div><a href="https://github.com/David-Edmonds">GitHub</a><a href="https://www.linkedin.com/in/david-edmonds">LinkedIn</a><a href="#top">Back to top ↑</a></div><small>© {new Date().getFullYear()} David Edmonds. Portfolio examples use sanitized data.</small></footer>
 </main>
}
function Header({n,a,b}:{n:string,a:string,b:string}){return <div className="heading"><small>{n}</small><h2>{a}<br/><em>{b}</em></h2></div>}
function Kicker(){return <small className="green">PRIVATE / LOCAL</small>}
